# Generated by Django 2.1.1 on 2018-10-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollywood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.PositiveIntegerField(default=120),
            preserve_default=False,
        ),
    ]
