# Generated by Django 2.1.1 on 2018-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollywood', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='post_thumbs/default_thumb.jpg', upload_to='post_thumbs'),
        ),
    ]
