# Generated by Django 2.1.1 on 2018-11-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollywood', '0005_auto_20181109_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auth',
            new_name='author',
        ),
    ]
