# Generated by Django 2.1.1 on 2018-11-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollywood', '0008_auto_20181111_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='auth',
        ),
    ]
