# Generated by Django 2.1.1 on 2018-11-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20181117_1357'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('jollywood', '0010_auto_20181113_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
