# Generated by Django 2.1.1 on 2018-11-22 15:43

from django.db import migrations, models
import jollywood.models


class Migration(migrations.Migration):

    dependencies = [
        ('jollywood', '0011_auto_20181117_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Pre-Intermediate', 'Pre-Intermediate'), ('Intermediate', 'Intermediate'), ('Upper-Intermediate', 'Upper-Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('cover', models.ImageField(default='book_thumbs/default_cover.jpg', upload_to='book_thumbs')),
                ('book', models.FileField(upload_to=jollywood.models.file_upload_path)),
            ],
        ),
    ]
