# Generated by Django 2.1.1 on 2018-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollywood', '0012_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Grammar', 'Grammar'), ('Vocabulary', 'Vocabulary'), ('Story', 'Story')], default='Grammar', max_length=20),
        ),
    ]
