# Generated by Django 2.1.1 on 2018-10-31 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ma', 'Mathematics')], default='en', max_length=2)),
                ('level', models.CharField(choices=[('beg', 'Beginner'), ('elem', 'Elementary'), ('pre', 'Pre-Intermediate'), ('inter', 'Intermediate'), ('upper', 'Upper-Intermediate'), ('adv', 'Advanced')], default='beg', max_length=5)),
                ('title', models.CharField(choices=[('t', 'Teacher'), ('s', 'Student')], default='s', max_length=1)),
                ('avatar', models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
