# Generated by Django 2.1.1 on 2018-11-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.CharField(choices=[('fa-user', 'User'), ('student', 'Student'), ('ninja', 'Ninja'), ('tie', 'Tie'), ('doc', 'Doctor'), ('ast', 'Astronaut'), ('spy', 'Spy'), ('injured', 'Injured')], default='user', max_length=150),
        ),
    ]
