# Generated by Django 2.1.1 on 2018-11-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181101_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.CharField(choices=[('fa-user', 'User'), ('fa-user-graduate', 'Student'), ('fa-user-ninja', 'Ninja'), ('fa-user-tie', 'Tie'), ('fa-user-md', 'Doctor'), ('fa-user-astronaut', 'Astronaut'), ('fa-user-secret', 'Spy'), ('fa-user-injured', 'Injured')], default='fa-user', max_length=150),
        ),
    ]
