# Generated by Django 2.1.1 on 2018-11-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('Mathematics', 'Mathematics')], default='English', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Pre-Intermediate', 'Pre-Intermediate'), ('Intermediate', 'Intermediate'), ('Upper-Intermediate', 'Upper-Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='s', max_length=1),
        ),
    ]
