# Generated by Django 2.1.1 on 2018-11-09 11:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user', '0012_auto_20181103_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('Mathematics', 'Mathematics')], default='English', max_length=20)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Pre-Intermediate', 'Pre-Intermediate'), ('Intermediate', 'Intermediate'), ('Upper-Intermediate', 'Upper-Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('title', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=20)),
                ('avatar', models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars')),
                ('icon', models.CharField(choices=[('fa-user', 'User'), ('fa-user-graduate', 'Student'), ('fa-user-ninja', 'Ninja'), ('fa-user-tie', 'Tie'), ('fa-user-md', 'Doctor'), ('fa-user-astronaut', 'Astronaut'), ('fa-user-secret', 'Spy'), ('fa-user-injured', 'Injured')], default='fa-user', max_length=150)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
